version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - D:/E-Porfolio/db:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
      - frontend
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      command: start-dev --db=postgres --db-url=jdbc:postgresql://postgres:5432/keycloak --db-username=keycloak --db-password=password
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 8080:8080
      depends_on:
        - postgres
      networks:
      - frontend

networks:
  frontend: